apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: talk-with-neighbors
resources:
  - namespace.yaml
  - mysql.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
