version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types: ["version-update:semver-major"]
      - dependency-name: "gradle-wrapper"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: "/infra/aws-ec2"
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
