version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: "/infra/aws-ec2"
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
