spring:
  application:
    name: talkWithNeighbors
  mandatory-file-encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/talk_with_neighbors?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&readOnlyPropagatesToServer=false&autoReconnect=true&defaultTransactionIsolation=READ_COMMITTED
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_COMMITTED
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: false
          autocommit: false
        jdbc:
          time_zone: UTC
          batch_size: 30
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
    open-in-view: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on-save
    cookie:
      http-only: true
      secure: false
      max-age: 86400 # 24시간
      same-site: lax
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 2000ms
      connect-timeout: 2000ms
      client-type: lettuce
      password:  # 비밀번호 설정 제거
    jpa:
      repositories:
        enabled: true
  config:
    import: optional:application-secret.yml

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        name: SESSIONID
        http-only: true
        secure: false
        same-site: lax
        path: /
        max-age: 86400
    encoding:
      charset: UTF-8
      force: true
      enabled: true

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.talkwithneighbors: DEBUG
    org.springframework.messaging: TRACE
    org.springframework.web.socket: TRACE
    org.springframework.messaging.simp: TRACE
    org.springframework.messaging.simp.broker: TRACE
    org.springframework.messaging.simp.user: TRACE
    org.springframework.messaging.simp.stomp: TRACE
    org.springframework.messaging.converter: TRACE
    org.springframework.messaging.core: TRACE
    org.springframework.messaging.support: TRACE
    org.springframework.web.socket.sockjs: TRACE
    org.springframework.web.socket.adapter: TRACE
    org.springframework.web.socket.handler: TRACE
    # === SimpleBroker 구독 레지스트리 상세 로깅 ===
    org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry: TRACE
    org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: TRACE
    ROOT: WARN  # 다른 로그 노이즈 줄이기

jwt:
  secret: your-jwt-secret-key
  expiration: 86400000